const $ = id => document.getElementById(id);
const state = { file:null, camera:null, history:[], score:null, lastResult:null, apiUrl:localStorage.getItem('sg_api_url')||'http://localhost:8000', userId:localStorage.getItem('sg_user_id')||'household_402', wardId:localStorage.getItem('sg_ward_id')||'Ward-12 (Delhi)' };
const sampleResults = [
 {item_detected:"Clean PET Water Bottle",category:"Dry Recyclable",is_contaminated:false,is_segregation_correct:true,box_color:"green",contamination_reason:null,correct_bin:"Blue Bin (Recyclables)",bin_color:"Blue",action_required:"Clean dry recyclable verified. Safe to discard in the Blue Bin.",points_awarded:15,material:"Polyethylene Terephthalate (PET #1)",remediation_steps:["Empty any remaining liquid","Keep the cap attached where local rules allow","Crush the bottle and place it in the Blue Bin"],confidence_score:.98,environmental_impact_tip:"Recycling PET plastic can reduce the energy needed compared with producing virgin plastic.",scan_id:"demo_scan_01",engine_source:"SegregateGuard Demo",user_score:{total_points:115,total_scans:1,correct_scans:1,contamination_prevented:0,segregation_accuracy_pct:100}},
 {item_detected:"Greasy Cardboard Pizza Box",category:"Sanitary / Landfill",is_contaminated:true,is_segregation_correct:false,box_color:"red",contamination_reason:"Food grease can contaminate paper fibres and lower recycling quality.",correct_bin:"Black Bin (Landfill / Soiled Waste)",bin_color:"Black",action_required:"Separate clean cardboard from the greasy section. Dispose of heavily soiled cardboard according to local rules.",points_awarded:-5,material:"Corrugated cardboard (grease-soaked)",remediation_steps:["Remove any clean, dry lid or sections","Keep greasy sections out of the clean paper stream","Follow local waste collection guidance"],confidence_score:.96,environmental_impact_tip:"Keeping food residue out of paper recycling helps protect the quality of recovered fibre.",scan_id:"demo_scan_02",engine_source:"SegregateGuard Demo",user_score:{total_points:95,total_scans:1,correct_scans:0,contamination_prevented:1,segregation_accuracy_pct:0}}
];
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200)}
function api(path){return state.apiUrl.replace(/\/+$/,'')+path}
function showView(view){const names={overview:'Overview',scanner:'Smart scanner',insights:'Impact insights',guide:'Sorting guide'};$('crumbName').textContent=names[view]||'Overview';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='scanner')$('scannerPanel').scrollIntoView({behavior:'smooth',block:'center'});if(view==='guide')document.querySelector('.bins-panel').scrollIntoView({behavior:'smooth',block:'center'});if(view==='insights')document.querySelector('.lower-grid').scrollIntoView({behavior:'smooth',block:'start'});}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>showView(el.dataset.view)));
function setStatus(text,ok=false){$('connectionText').textContent=text;$('connectionText').parentElement.classList.toggle('connected',ok)}
function renderScore(s){if(!s)return;$('scoreValue').innerHTML=`${s.total_points??100}<span> pts</span>`;$('scansValue').textContent=s.total_scans??0;$('accuracyValue').innerHTML=`${Number(s.segregation_accuracy_pct??100).toFixed(1).replace('.0','')}<span>%</span>`;$('accuracyBar').style.width=Math.max(0,Math.min(100,Number(s.segregation_accuracy_pct??100)))+'%';$('preventedValue').textContent=s.contamination_prevented??0;$('accuracyLabel').textContent=Number(s.segregation_accuracy_pct??100)>=90?'Excellent work':Number(s.segregation_accuracy_pct??100)>=70?'Getting better':'Room to improve';state.score=s}
async function checkConnection(){try{const r=await fetch(api('/health'),{signal:AbortSignal.timeout(3500)});if(!r.ok)throw Error('API responded '+r.status);const d=await r.json();setStatus(d.mock_mode?'API connected · simulation':'API connected',true);return true}catch(e){setStatus('API offline',false);return false}}
async function loadScore(){try{const r=await fetch(api('/api/user/score?user_id='+encodeURIComponent(state.userId),{signal:AbortSignal.timeout(4000)}));if(!r.ok)throw Error();renderScore(await r.json())}catch(e){renderScore(state.score||{total_points:100,total_scans:0,contamination_prevented:0,segregation_accuracy_pct:100})}}
function setFile(file){if(!file)return;if(!file.type.startsWith('image/')){toast('Please choose an image file.');return}if(file.size>12*1024*1024){toast('Please use an image smaller than 12 MB.');return}state.file=file;stopCamera();const url=URL.createObjectURL(file);$('previewImage').src=url;$('previewImage').hidden=false;$('cameraVideo').hidden=true;$('stagePlaceholder').hidden=true;$('imageLabel').hidden=false;$('cameraOverlay').hidden=true;$('scanBtn').disabled=false;$('dropZone').classList.remove('scanning');toast('Image ready. Inspect it when you are ready.')}
$('uploadBtn').addEventListener('click',()=>$('fileInput').click());$('fileInput').addEventListener('change',e=>setFile(e.target.files[0]));
$('dropZone').addEventListener('dragover',e=>{e.preventDefault();$('dropZone').style.borderColor='#6aa36a'});$('dropZone').addEventListener('dragleave',()=> $('dropZone').style.borderColor='');$('dropZone').addEventListener('drop',e=>{e.preventDefault();$('dropZone').style.borderColor='';setFile(e.dataTransfer.files[0])});
async function stopCamera(){if(state.camera){state.camera.getTracks().forEach(t=>t.stop());state.camera=null}if($('cameraVideo').srcObject)$('cameraVideo').srcObject=null;$('cameraOverlay').hidden=true}
$('cameraBtn').addEventListener('click',async()=>{if(state.camera){stopCamera();$('cameraVideo').hidden=true;$('stagePlaceholder').hidden=false;$('scanBtn').disabled=true;$('previewImage').hidden=true;$('imageLabel').hidden=true;$('cameraBtn').innerHTML='<span>◎</span> Use camera';return}try{state.camera=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});$('cameraVideo').srcObject=state.camera;$('cameraVideo').hidden=false;$('previewImage').hidden=true;$('stagePlaceholder').hidden=true;$('cameraOverlay').hidden=false;$('imageLabel').hidden=true;$('scanBtn').disabled=false;$('cameraBtn').innerHTML='<span>×</span> Stop camera';state.file=null;toast('Camera is live. Capture a frame to inspect.')}catch(e){toast('Camera unavailable. Allow camera access or upload a photo.')}});
function captureCamera(){return new Promise((resolve,reject)=>{const v=$('cameraVideo');if(!state.camera||v.videoWidth===0)return reject(Error('Camera is not ready'));const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);c.toBlob(b=>{if(!b)return reject(Error('Could not capture camera frame'));resolve(new File([b],'camera-capture.jpg',{type:'image/jpeg'}))},'image/jpeg',.9)})}
$('scanBtn').addEventListener('click',async()=>{try{if(state.camera&&!state.file)state.file=await captureCamera();if(!state.file){toast('Upload a photo or turn on your camera first.');return}await inspectFile(state.file)}catch(e){toast(e.message||'Could not capture image.')}});
async function inspectFile(file){$('scanBtn').disabled=true;$('scanBtn').innerHTML='<span>◌</span> Inspecting…';$('dropZone').classList.add('scanning');$('emptyResult').hidden=false;$('emptyResult').innerHTML='<div class="empty-symbol">◌</div><strong>Reading your item…</strong><p>Checking material, contamination and the recommended destination.</p><div class="empty-points"><span>01 <small>ANALYSE</small></span><span>02 <small>VERIFY</small></span><span>03 <small>ADVISE</small></span></div>';$('resultContent').hidden=true;let result;try{const fd=new FormData();fd.append('file',file);const params=new URLSearchParams({target_bin:$('targetBin').value,user_id:state.userId,ward_id:state.wardId,location_context:'India - Municipal Solid Waste'});const response=await fetch(api('/api/inspect/upload?'+params.toString()),{method:'POST',body:fd,signal:AbortSignal.timeout(45000)});if(!response.ok){let msg='Inspection failed ('+response.status+')';try{msg=(await response.json()).detail||msg}catch{}throw Error(msg)}result=await response.json();setStatus('API connected',true);toast('Inspection complete. Results are ready.')}catch(err){result=sampleResults[Math.floor(Math.random()*sampleResults.length)];result={...result,scan_id:'demo_'+Date.now().toString(36)};result._demo=true;toast('Backend unavailable — showing clearly labelled demo data. Configure API in ⚙ to use live AI.')}finally{$('scanBtn').disabled=false;$('scanBtn').innerHTML='<span>✦</span> Inspect item';$('dropZone').classList.remove('scanning');if(state.camera)stopCamera()}
renderResult(result);if(!result._demo){if(result.user_score)renderScore(result.user_score);else loadScore()}else{const old=state.score||{total_points:100,total_scans:0,contamination_prevented:0,segregation_accuracy_pct:100};renderScore({...old,total_scans:(old.total_scans||0)+1,total_points:Math.max(0,(old.total_points||100)+(result.points_awarded||0)),contamination_prevented:(old.contamination_prevented||0)+(result.is_contaminated?1:0),segregation_accuracy_pct:result.is_segregation_correct?Math.min(100,((old.total_scans||0)*(old.segregation_accuracy_pct||100)+100)/((old.total_scans||0)+1)):Math.max(0,((old.total_scans||0)*(old.segregation_accuracy_pct||100))/((old.total_scans||0)+1))})}addHistory(result)}
function renderResult(r){state.lastResult=r;$('emptyResult').hidden=true;$('resultContent').hidden=false;$('resultIndex').textContent='# '+(r.scan_id||'SCAN').slice(-6).toUpperCase();const good=!!r.is_segregation_correct;$('resultStatus').classList.toggle('bad',!good);$('resultStatus').querySelector('.result-check').textContent=good?'✓':'!';$('resultHeadline').textContent=good?'Segregation looks correct':'Action recommended';$('confidence').textContent=Math.round((r.confidence_score??.95)*100)+'% confidence';$('itemName').textContent=r.item_detected||'Item inspected';$('itemDescription').textContent=r.contamination_reason||'No contamination issue was reported for this item.';$('categoryTag').textContent=(r.category||'General waste').toUpperCase();$('materialTag').textContent=r.material||'MATERIAL IDENTIFIED';$('correctBin').textContent=r.correct_bin||'Check local waste guidance';$('actionRequired').textContent=r.action_required||'Follow local waste collection rules.';const color=String(r.bin_color||'Blue').toLowerCase();const colors={blue:['#e4efff','#3775b8'],green:['#e5f4e5','#39864b'],yellow:['#fff2d4','#b58524'],red:['#ffebe7','#bc5145'],black:['#e8ece9','#37463d']};const pair=colors[color]||colors.blue;$('binIllustration').style.background=pair[0];$('binIllustration').style.color=pair[1];$('stepsList').innerHTML='';(r.remediation_steps||[]).forEach((s,i)=>{const row=document.createElement('div');row.className='step-item';row.innerHTML=`<span class="step-number">${String(i+1).padStart(2,'0')}</span><span></span>`;row.lastElementChild.textContent=s;$('stepsList').appendChild(row)});if(!(r.remediation_steps||[]).length)$('stepsList').textContent='No additional steps provided.';$('impactTip').textContent=r.environmental_impact_tip||'Correct sorting helps keep recyclable materials useful.';$('pointsEarned').textContent=((r.points_awarded||0)>0?'+':'')+(r.points_awarded||0)+' points';$('scanId').textContent=r._demo?'DEMO RESULT':(r.scan_id||'');if(r._demo){$('resultHeadline').textContent='Demo result · not live AI';$('confidence').textContent='Illustrative data';$('scanId').textContent='DEMO ONLY'} }
function addHistory(r){state.history.unshift({name:r.item_detected||'Unknown item',category:r.category||'Waste',points:r.points_awarded||0,good:!!r.is_segregation_correct,time:new Date(),demo:!!r._demo});state.history=state.history.slice(0,6);renderHistory()}
function renderHistory(){$('historyList').innerHTML='';if(!state.history.length){$('historyList').innerHTML='<div class="history-empty">No scans yet. Your inspection trail will appear here.</div>';return}state.history.forEach(h=>{const el=document.createElement('div');el.className='history-item';const icon=h.good?'✓':'!';const time=h.time.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});el.innerHTML=`<span class="history-icon">${icon}</span><div><strong></strong><small></small></div><span class="history-points ${h.points<0?'negative':''}"></span>`;el.children[1].children[0].textContent=h.name;el.children[1].children[1].textContent=`${h.category} · ${time}${h.demo?' · demo':''}`;el.children[2].textContent=(h.points>0?'+':'')+h.points+' pts';$('historyList').appendChild(el)})}
$('clearHistoryBtn').addEventListener('click',()=>{state.history=[];renderHistory();toast('Local activity list cleared.')});
function openSettings(){$('apiUrl').value=state.apiUrl;$('userId').value=state.userId;$('wardId').value=state.wardId;$('settingsModal').hidden=false}
$('settingsBtn').addEventListener('click',openSettings);$('closeSettings').addEventListener('click',()=>$('settingsModal').hidden=true);$('settingsModal').addEventListener('click',e=>{if(e.target===$('settingsModal'))$('settingsModal').hidden=true});
$('saveSettingsBtn').addEventListener('click',async()=>{state.apiUrl=$('apiUrl').value.trim().replace(/\/+$/,'');state.userId=$('userId').value.trim()||'household_402';state.wardId=$('wardId').value.trim()||'Ward-12 (Delhi)';localStorage.setItem('sg_api_url',state.apiUrl);localStorage.setItem('sg_user_id',state.userId);localStorage.setItem('sg_ward_id',state.wardId);$('profileId').textContent=state.userId;$('settingsModal').hidden=true;await checkConnection();await loadScore();toast('Settings saved in this browser.')});
$('testApiBtn').addEventListener('click',async()=>{const old=state.apiUrl;state.apiUrl=$('apiUrl').value.trim().replace(/\/+$/,'');const ok=await checkConnection();if(ok)toast('Backend is reachable.');else toast('Could not reach backend. Check URL, server and CORS settings.');if(!ok)state.apiUrl=old});
$('refreshBtn').addEventListener('click',async()=>{await checkConnection();await loadScore();toast('Dashboard refreshed.')});
$('todayDate').textContent=new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase();
$('profileId').textContent=state.userId;
renderScore({total_points:100,total_scans:0,contamination_prevented:0,segregation_accuracy_pct:100});checkConnection().then(loadScore);
